# Generated by Django 3.0.5 on 2020-04-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='account',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_started',
        ),
        migrations.AddField(
            model_name='campaign',
            name='identifier',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
