# Generated by Django 3.0.5 on 2020-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(1, 'Coordinator'), (2, 'Manufacturer'), (3, 'Courier'), (4, 'Admin'), (5, 'Reciever')]),
        ),
    ]
