# Generated by Django 3.0.5 on 2020-04-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200427_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='displayName',
            field=models.CharField(default='john', max_length=150, unique=True),
        ),
    ]
